FROM docker.io/golang:1.25.7 AS daemon-builder
WORKDIR /go/src/github.com/k8snetworkplumbingwg/ptp-operator
ENV GOMAXPROCS=16
ENV GO111MODULE=on

# Copy from the operator checkout (build context is OPERATOR_ROOT).
COPY . .

WORKDIR /go/src/github.com/k8snetworkplumbingwg/ptp-operator/pkg/linuxptp-daemon

RUN ./hack/cleanup.sh && \
    (go build -ldflags "-X main.GitCommit=$(git rev-list -1 HEAD 2>/dev/null || echo unknown)" --mod=vendor -o bin/ptp ./cmd || go build -o bin/ptp ./cmd) && \
    (go build -ldflags "-X main.GitCommit=$(git rev-list -1 HEAD 2>/dev/null || echo unknown)" --mod=vendor -o bin/cloud-event-proxy ./cmd/cloud-event-proxy || go build -o bin/cloud-event-proxy ./cmd/cloud-event-proxy || true)

FROM quay.io/centos/centos:stream9
ARG LINUXPTP_RPM=""

RUN yum -y update && yum --setopt=skip_missing_names_on_install=False -y install \
    linuxptp ethtool hwdata synce4l procps-ng chrony \
    gpsd-minimal gpsd-minimal-clients && yum clean all

COPY ptp-tools/extra/ /tmp/extra/
RUN if [ -n "${LINUXPTP_RPM}" ]; then \
      echo "=== Installing custom linuxptp RPM: ${LINUXPTP_RPM} ===" \
      && rpm -Uvh --force /tmp/extra/${LINUXPTP_RPM} \
      && rm -rf /tmp/extra; \
    fi

# CI stand-in virtual CLOCK_REALTIME: phc2sys wrapper + LD_PRELOAD shim.
# Active only when /var/run/vrt/device (or PTP_VRT_PHC) points at a mock PHC.
COPY scripts/ptp-vrt/ /tmp/ptp-vrt/
RUN yum -y install gcc make && \
    make -C /tmp/ptp-vrt && \
    install -m 755 /tmp/ptp-vrt/libptp_vrt_shim.so /usr/local/lib/ && \
    mv /usr/sbin/phc2sys /usr/sbin/phc2sys.real && \
    install -m 755 /tmp/ptp-vrt/phc2sys-wrapper /usr/sbin/phc2sys && \
    rm -rf /tmp/ptp-vrt && \
    yum -y remove gcc make && yum clean all

RUN ln -sf /usr/bin/gpspipe /usr/local/bin/gpspipe && \
    ln -sf /usr/sbin/gpsd /usr/local/sbin/gpsd && \
    ln -sf /usr/bin/ubxtool /usr/local/bin/ubxtool

COPY --from=daemon-builder /go/src/github.com/k8snetworkplumbingwg/ptp-operator/pkg/linuxptp-daemon/bin/ptp /usr/local/bin/

CMD ["/usr/local/bin/ptp"]
